name: 'Warpd action'
description: 'Build and deploy'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get build matrix
      id: get_matrix
      uses: docker://docker.io/gp42/warpd:main
      with:
        args: github buildmatrix -c testdata/example/warpd.yaml
    - name: Echo matrix
      shell: bash
      run: echo '${{ steps.get_matrix.outputs.matrix }}'
    - name: Run Builder
      id: builder
      uses: ops42-org/warpd/github-builder@main
    - name: Run Deployer
      id: deployer
      uses: ops42-org/warpd/github-deployer@main