name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/gp42/warpd-builder
          tags: |
            type=ref,event=branch
            type=sha,prefix=,format=long
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_GP42_USERNAME }}
          password: ${{ secrets.DOCKERHUB_GP42_TOKEN }}
      -
        name: Build and push - Builder
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          images: docker.io/gp42/warpd-builder
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile-builder
      -
        name: Build and push - Deployer
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          images: docker.io/gp42/warpd-deployer
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile-deployer
