on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display the environment variables and their values
        run: |
          echo foobarz
        shell: bash
      - name: Run Builder
        id: builder
        uses: ops42-org/warpd-github-builder-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Run Deployer
        id: deployer
        uses: ops42-org/warpd-github-deployer-action@main
        with:
          who-to-greet: 'Mona the Octocat'
