on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Builder
        id: builder
        uses: ops42-org/warpd/github-builder@main

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Deployer
        id: deployer
        uses: ops42-org/warpd/github-deployer@main

