on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display the environment variables and their values
        run: |
          echo foobarz
        shell: bash
      - name: Run Builder
        id: builder
        uses: ops42-org/warpd/.github/actions/warpd-builder/action.yaml@main
