on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Builder
        id: builder
        uses: ops42-org/warpd/github-builder@main
        with:
          who-to-greet: 'Mona the Octocat'

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Deployer
        id: deployer
        uses: ops42-org/warpd-github-deployer-action@main
        with:
          who-to-greet: 'Mona the Octocat'

