on:
  workflow_call:

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get build matrix
        id: get_matrix
        uses: docker://docker.io/gp42/warpd:main
        with:
          args: github buildmatrix

  build:
    needs: build_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build_matrix.outputs.matrix)}}
    steps:
      - name: Run Buildpacks
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: ${{ matrix.Name }}
          tag: '1.0.0'
          path: ${{ matrix.Path }}
          builder: 'gcr.io/paketo-buildpacks/builder:base'        

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Run Builder
  #       id: builder
  #       uses: ops42-org/warpd/github-builder@main

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Run Deployer
  #       id: deployer
  #       uses: ops42-org/warpd/github-deployer@main

